Fixes: Fatal Error when running PHP lint command
```bash
Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script in psalm/stubs/imagick.php on line 11
```

Recreate:
`php -l psalm/stubs/imagick.php`

Expect:
`No syntax errors detected in psalm/stubs/imagick.php`